sudo: required
services:
  - docker

before_install:
  - docker build -t davveee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davveee/react-test npm test

after_success:
  - docker build -t davveee/multi-client ./client
  - docker build -t davveee/multi-nginx ./nginx
  - docker build -t davveee/multi-server ./server
  - docker build -t davveee/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin

  - docker push davveee/multi-client
  - docker push davveee/multi-nginx
  - docker push davveee/multi-server
  - docker push davveee/multi-worker